# 1. Uses mysql database
# 2. Schema is created using scheme.sql
# 3. Database is populated with test data from data.sql

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/obo-dev
    username: root
    password: admin
#    not necessary
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      # We're using schema.sql
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      platform: mysql

logging:
  level:
    org:
      hibernate:
#        SQL: debug
        # This logs values too
        type: trace
